### ISSUE TITLE
Documentation: How "pdbp" (Pdb+) began.

### ISSUE THREAD

**Issue by mdmintz** [mdmintz/pdbp#1]
### Documentation: How "pdbp" (**Pdb+**) began.

See https://github.com/seleniumbase/SeleniumBase/issues/1623 for all the details.

**Comment by mdmintz** [comment]
### Example:

<img width="858" alt="Screenshot 2022-11-28 at 4 30 20 PM" src="https://user-images.githubusercontent.com/6788579/204386188-81189c37-93c0-4204-8092-f05f0be5dbd0.png">

### Commands:

<img width="860" alt="Screenshot 2022-11-28 at 4 33 54 PM" src="https://user-images.githubusercontent.com/6788579/204386211-5fc44f73-e29f-4e87-b0ca-bb8ea69217af.png">

**Comment by mdmintz** [comment]
<img width="940" alt="Screenshot 2022-11-28 at 7 24 03 PM" src="https://user-images.githubusercontent.com/6788579/204408641-9c221bb6-578b-4b0f-807b-8454844e42e8.png">

**Comment by mdmintz** [comment]
<img width="850" alt="Screenshot 2022-12-14 at 11 45 20 PM" src="https://user-images.githubusercontent.com/6788579/207774790-fb63af65-5f98-4d92-afe3-12c2733d4db6.png">

**Comment by lazka** [comment]
For completeness sake I think it should be noted that this project started as a copy of https://github.com/pdbpp/pdbpp with all comments, copyright and license information removed.

**Comment by jubalfh** [comment]
@lazka opened #65 to get some clarity on the attribution and copyright.
