### ISSUE TITLE
support `python -m pdbp <script.py>`?

### ISSUE THREAD

**Issue by davidszotten** [mdmintz/pdbp#20]
currently crashes

**Comment by mdmintz** [comment]
I see the issue. I can ship a new release with the feature/fix this Tuesday or Wednesday.

**Comment by davidszotten** [comment]
that would be awesome, thanks! (no rush though)

**Comment by mdmintz** [comment]
This was resolved in ``1.3.0`` - https://github.com/mdmintz/pdbp/releases/tag/v1.3.0

**Comment by mdmintz** [comment]
@davidszotten Any issues after upgrading and running?

**Comment by davidszotten** [comment]
seems to work. thanks! 🎉
