### ISSUE TITLE
Feat request: highlight the "current stack frame" in the `w`/`where`/`bt` output?

### ISSUE THREAD

**Issue by goodboy** [mdmintz/pdbp#32]
As per our mini discussion in the `tractor` matrix room:
https://matrix.to/#/!scerhxskQIIRMpggqm:matrix.org/$slaV-GyCnC5Bbt3-IDn41aDJGsMJ4xfZoiZznBY3GrQ?via=matrix.org&via=gitter.im&via=ancap.tech

It'd be handy to have a visual indicator of the current frame particularly when stepping through frames using `u`/`d`/`f <frame#>`.

Currently there is a `>` char prefix (which came from `pdbpp` afaiu) but it'd nice to have something with a little more "pop" for the human eye too 😉 

----
To give a visual eg. stepping through a bt in one of our multi-actor debugger scripts:

![screenshot-2023-04-19_10-51-13](https://user-images.githubusercontent.com/291685/233114464-7fcb0c29-efb6-4e55-967d-4657712eaac1.png)

As you can see, it's kinda hard to notice the chevron by first glance.

**Comment by mdmintz** [comment]
Resolved in ``1.3.1`` - https://github.com/mdmintz/pdbp/releases/tag/v1.3.1
