### ISSUE TITLE
Documenting using PYTHONBREAKPOINT

### ISSUE THREAD

**Issue by DavideCanton** [mdmintz/pdbp#40]
Maybe it may make sense to add something in the README regarding the possiblity of registering pdbp using `PYTHONBREAKPOINT="pdbp.set_trace"` as an alternative to importing pdbp in the source code?

**Comment by mdmintz** [comment]
Good idea. I can add that to the ReadMe. Something with:

PYTHONBREAKPOINT
If this is set, it names a callable using dotted-path notation. The module containing the callable will be imported and then the callable will be run by the default implementation of [sys.breakpointhook()](https://docs.python.org/3/library/sys.html#sys.breakpointhook) which itself is called by built-in [breakpoint()](https://docs.python.org/3/library/functions.html#breakpoint). If not set, or set to the empty string, it is equivalent to the value “pdb.set_trace”. Setting this to the string “0” causes the default implementation of [sys.breakpointhook()](https://docs.python.org/3/library/sys.html#sys.breakpointhook) to do nothing but return immediately.
New in version 3.7.

Probably by tomorrow or very soon.

**Comment by DavideCanton** [comment]
Hi, thanks for your response!

I think that an example (like the one I provided) could help people like me that didn't know `PYTHONBREAKPOINT` :)

**Comment by mdmintz** [comment]
@DavideCanton I made a few updates to the ReadMe to include this! https://github.com/mdmintz/pdbp/blob/master/README.md
