### ISSUE TITLE
'current_line_color' is reset to default value when Exception is caught

### ISSUE THREAD

**Issue by Sharpeee** [mdmintz/pdbp#42]
When running this code
```python
import pdb
import pdbp

if hasattr(pdb, "DefaultConfig"):
    pdb.DefaultConfig.current_line_color = None

pdbp.set_trace()
print("Correct line colour")

foo = {'a': 1}
try:
    print(foo['b'])
except Exception:
    print(foo['a'])

print("Wrong line colour")
```
The line colour is reset to the default value at the `print(foo['a'])` line. The variable `pdb.DefaultConfig.current_line_color` is however not reset.

**Comment by Sharpeee** [comment]
Okay, so I just spent 10 minutes actually looking into the problem, and the problem is in [pdbp.py:295](https://github.com/mdmintz/pdbp/blob/master/src/pdbp.py#L295).

```
self.config.current_line_color = self.config.regular_line_color
```

The workaround for this is to set both `current_line_color` and `regular_line_color` in the DefaultConfig. The "more correct" solution would probably be something like

```
self.config.regular_line_color = self.config.current_line_color
```

in `__init__`.

**Comment by mdmintz** [comment]
The current behavior is correct. If an exception is caught / handled, then you are no longer in Post Mortem Debug Mode (where you have an unhandled exception). Then you are just in regular Debug Mode, where program execution can continue. Therefore, the highlighted lines should return to blue. When stepping through lines, if there's an exception, the line should turn red. If handled, we make note of where the last exception was caught/handled by turning the line yellow. The current line then becomes blue as expected.

<img width="355" alt="Screenshot 2023-06-27 at 8 56 21 AM" src="https://github.com/mdmintz/pdbp/assets/6788579/c538f305-7787-4c7e-98df-3de7035f722a">

<img width="372" alt="Screenshot 2023-06-27 at 8 58 18 AM" src="https://github.com/mdmintz/pdbp/assets/6788579/6929a802-ce60-40dc-b876-510d0c1c6b92">

**Comment by Sharpeee** [comment]
Maybe I didn't explain myself good enough.

In your example you commented out some very important lines. In those lines I set the line colour to `None`, because I don't want to highlight the current line with a background colour.
Then when the Exception has been caught, whatever colour I chose (or `None` in this case), is overwritten and the default blue colour shows up again.

**Comment by mdmintz** [comment]
These are the colors you can change:

```python
    filename_color = Color.fuchsia
    line_number_color = Color.turquoise
    regular_stack_color = Color.yellow
    pm_stack_color = Color.red
    return_value_color = "90;1"  # Gray
    pm_return_value_color = "31;1"  # Red (Post Mortem failure)
    num_return_value_color = "95;1"  # Bright Magenta (numbers)
    true_return_value_color = "32;1"  # Green
    false_return_value_color = "33;1"  # Yellow (red was taken)
    none_return_value_color = "33;1"  # Yellow (same as False)
    regular_line_color = "97;44;1"  # White on Blue (Old: "39;49;7")
    pm_cur_line_color = "97;41;1"  # White on Red (Post Mortem Color)
    exc_line_color = "31;103;1"  # Red on Yellow (Exception-handling)
```

``pdb.DefaultConfig.current_line_color`` is a dynamic variable that changes based on the state of the active Debug Mode.

You could change `pdb.DefaultConfig.regular_line_color`.

If you are already in Debug Mode, then set `pdb.DefaultConfig.current_line_color` to be that color:

```python
if hasattr(pdb, "DefaultConfig"):
    pdb.DefaultConfig.regular_line_color = None
    pdb.DefaultConfig.current_line_color = None
```

If you later hit an exception in Debug Mode, the color would then change to the exception color defined above.

**Comment by Sharpeee** [comment]
Okay, that't helpful. Thank you.

Even if I set

```python
class Config(pdb.DefaultConfig):
    regular_line_color = None
```

in my `.pdbrc.py`, it's still not enough. Then the correct line colour will only show up after an Exception. So I have to do as you said

```python
class Config(pdb.DefaultConfig):
    regular_line_color = current_line_color = None
```

Maybe it would be a good idea if you set `self.config.current_line_color = self.config.regular_line_color` in `__init__`? Then the behaviour would be consistent.

**Comment by mdmintz** [comment]
It does get initialized by default here:

https://github.com/mdmintz/pdbp/blob/v1.4.1/src/pdbp.py#L128

Then users can change default settings in their ``__init__.py`` files.

**Comment by Sharpeee** [comment]
Yes, you initialise it in your DefaultConfig, but that doesn't help when I set it in my `.pdbrc.py`. Is this setup not supported and I **have** to set everything per project in my `__init__.py` file?

**Comment by mdmintz** [comment]
This line was carried over from the original version:

https://github.com/mdmintz/pdbp/blob/v1.4.1/src/pdbp.py#L182

But perhaps there was something else needed besides that.

If you can set things up in ``__init__.py``, then that's the way that's fully supported via the ReadMe documentation.
