### ISSUE TITLE
! statement doesn't support

### ISSUE THREAD

**Issue by mengban** [mdmintz/pdbp#53]
Excellent work!
But there is something is not as expected about `!` statement described here https://docs.python.org/3/library/pdb.html
when I want to assign values ​​to variables in debugging, it does't work.  
however, the pdb is ok.
Here is my env:
```
Linux   
Python==3.10.6
pdbp== 1.4.6 
```

**Comment by mdmintz** [comment]
From the documentation:

```
! statement

Execute the (one-line) statement in the context of the current stack frame.
The exclamation point can be omitted unless the first word of the statement resembles a debugger command.
```

With that, I took a debugger command, `frame`, and used the `!` statement to turn it into a variable:

<img width="950" alt="Screenshot 2023-08-21 at 5 31 03 AM" src="https://github.com/mdmintz/pdbp/assets/6788579/15560e3a-ce8d-4011-862c-5d2510031104">

I was able to use the `!` statement to turn a debugger command into a variable. What issue are you seeing?

The `!` statement should only be needed if using a debugger command as a variable.
