### ISSUE TITLE
Hide commands from history

### ISSUE THREAD

**Issue by bluss** [mdmintz/pdbp#60]
Is there a way to hide commands from command line history?

The background is that nvim-gdb is a frontend in neovim to Gdb and Pdb and it works with Pdbp too. It injects a break command invisibly between each interaction to update its state on breakpoints.

If there's a way to hide this from command history, nvim-gdb could make use of this. The annoyance is that this "break" shows up as the first item with up-arrow.

**Comment by mdmintz** [comment]
Not sure I fully understand your situation. Is this something that happens with regular `pdb` or `pdbpp` too?

I may need to see a screenshot to help. This is with neovim only?

**Comment by mdmintz** [comment]
Not sure how to reproduce this, but since it’s probably coming from the original pdb, this probably can’t be changed easily.
