### ISSUE TITLE
Autocomplete does not work

### ISSUE THREAD

**Issue by jonashaag** [mdmintz/pdbp#72]
I press Tab and nothing happens except for the terminal bell.

**Comment by mdmintz** [comment]
That may mean there's more than one auto-complete option available.
Try pressing the Tab key twice to see all possibilities.

**Comment by jonashaag** [comment]
Same result. It doesn't even show the pdb commands.

**Comment by mdmintz** [comment]
I think I see the issue. I'll ship a new release in the next 2 hours.

**Comment by mdmintz** [comment]
Upgrade to `1.6.1` - https://github.com/mdmintz/pdbp/releases/tag/v1.6.1

**Comment by jonashaag** [comment]
Now it works for builtins but not locals
<img width="348" alt="image" src="https://github.com/user-attachments/assets/1dbb307e-2bd4-4ca0-bcc0-96ddffb796e3">

**Comment by mdmintz** [comment]
You were using a regular `Pdb` debugger.
When `pdbp` is activated, it shows `(Pdb+)` in the console. You had `(Pdb)`.

----

When using **`pdbp`**, autocomplete is working correctly:

<img width="400" alt="Screenshot 2024-11-18 at 9 32 25 AM" src="https://github.com/user-attachments/assets/c0449223-e0da-4df1-b6c6-d9078a6288d6">

----

From regular `Pdb`, you need to use `dir()` in debug mode to list the variable scope.

Remember to include `import pdbp` in an `__init__.py` file to replace `pdb` with `pdbp`.
